apiVersion: v1
kind: Namespace
metadata:
  name: rwxtest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: rwxtest
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: rwxtest
spec:
  replicas: 30
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-pod
          image: registry.k8s.io/echoserver:1.4
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/rwx"
              name: my-pvc
              readOnly: false
      volumes:
        - name: my-pvc
          persistentVolumeClaim:
            claimName: my-pvc
